header:
  version: 14

distro: poky

repos:
  openembedded-core:
    url: https://git.openembedded.org/openembedded-core
    branch: scarthgap
    path: layers/openembedded-core
    layers:
      meta:

  meta-yocto:
    url: https://git.yoctoproject.org/meta-yocto
    branch: scarthgap
    path: layers/meta-yocto
    layers:
      meta-poky:
      meta-yocto-bsp:

  meta-openembedded:
    url: http://git.openembedded.org/meta-openembedded
    path: layers/meta-openembedded
    branch: scarthgap
    layers:
      meta-oe:
      meta-python:
      meta-networking:

  bitbake:
    url: https://git.openembedded.org/bitbake
    branch: "2.8"
    path: layers/bitbake
    layers:
      bitbake: disabled # Prevents kas from adding bitbake to BBLAYERS.

local_conf_header:
  common: |
    DL_DIR = "/yocto/downloads"
    SSTATE_DIR = "/yocto/sstate-cache"
  debug-tweaks: |
    IMAGE_FEATURES += "empty-root-password allow-empty-password allow-root-login post-install-logging"
